User.create(email: 'yumejitate@limetrd.co.jp', password: 'lime1946', nickname: 'Common')
User.create(email: 'sumihaya935@docomo.ne.jp', password: 'someno', nickname: 'Kumiko Someno')
User.create(email: 'toysrus7839spyoshi@docomo.ne.jp', password: 'shimogata', nickname: 'Yoshihiro Shimogata')
User.create(email: 'kzn-0126@ezweb.ne.jp', password: 'mori', nickname: 'Kazane Mori')
User.create(email: 'glass.skkin@icloud.com', password: 'suwabe', nickname: 'Kazuhiko Suwabe')
User.create(email: 'reiko.tanikawa0318@gmail.com', password: 'tanikawa', nickname: 'Reiko Tanikawa')
User.create(email: 'youkosan.0126@softbank.ne.jp', password: 'tsutsumi', nickname: 'Yoko Tsutsumi')
User.create(email: 'hmm_na-ch0bi.u_uzz.@docomo.ne.jp', password: 'yamamoto', nickname: 'Natsumi Yamamoto')
User.create(email: 'ichinenichikumi@limetrd.co.jp', password: 'lime1946', nickname: 'Mitsuhiro Yoda')
User.create(email: 'yuko@limetrd.co.jp', password: 'yuko1978', nickname: 'Yuko Yoda')

User.create(email: 'takahirono4444@gmail.com', password: 'taka3093', nickname: 'Takahiro Yoda')
