class AddColumnToproducts < ActiveRecord::Migration
  def change
      add_column :products, :user_id, :string#会員NO
      add_column :products, :sagyosyo_id, :string#作業所no
      add_column :products, :product_id, :string#商品no
      add_column :products, :name, :string#お客様名
      add_column :products, :name_rubi, :string#ふりがな
      add_column :products, :tel, :string
      add_column :products, :email, :string
      add_column :products, :post_no, :string
      add_column :products, :prefectures, :text#都道府県
      add_column :products, :adress1, :text
      add_column :products, :adress2, :text
      add_column :products, :free_space1, :text#備考欄
      add_column :products, :delete_box, :string#削除フラグ
      add_column :products, :first_day, :string#受注日※必須入力
      add_column :products, :shop, :string#受注場所
      add_column :products, :delivery_schedule, :string#納期-出来上り予定日※必須入力
      add_column :products, :delivery_string, :string#納品日-お客様お渡し日
      add_column :products, :sub_shop_delivery_string, :string#本社→現場-品物到着日
      add_column :products, :main_shop_delivery_string, :string#現場→本社-品物到着日
      add_column :products, :re_product_main_shop_delivery_string, :string#再加工売場→本社-品物到着日
      add_column :products, :re_product_sub_shop_delivery_string, :string#再加工本社→売場-品物到着日
      add_column :products, :matsuya_tsuuban, :string#通番-※松屋のみ
      add_column :products, :spesial_topics, :text#特記事項
      add_column :products, :product_prace1, :string#加工出先1
      add_column :products, :product_reason1, :string#加工内容1
      add_column :products, :product_first_day1, :string#出し日1
      add_column :products, :product_delivery_schedule1, :string#ﾗｲﾑ納期1
      add_column :products, :product_delivery_day1, :string#受取日1
      add_column :products, :product_prace2, :string#加工出先2
      add_column :products, :product_reason2, :string#加工内容2
      add_column :products, :product_first_day2, :string#出し日2
      add_column :products, :product_delivery_schedule2, :string#ﾗｲﾑ納期2
      add_column :products, :product_delivery_day2, :string#受取日2
      add_column :products, :product_prace3, :string#加工出先3
      add_column :products, :product_reason3, :string#加工内容3
      add_column :products, :product_first_day3, :string#出し日3
      add_column :products, :product_delivery_schedule3, :string#ﾗｲﾑ納期3
      add_column :products, :product_delivery_day3, :string#受取日3
      add_column :products, :product_prace4, :string#加工内容4
      add_column :products, :product_first_day4, :string#出し日4
      add_column :products, :product_delivery_schedule4, :string#ﾗｲﾑ納期4
      add_column :products, :product_delivery_day4, :string#受取日4
      add_column :products, :luggage_goods, :string#預かり品詳細
      add_column :products, :product_name, :string#受注商品名
      add_column :products, :design_no, :string#ﾃﾞｻﾞｲﾝNo
      add_column :products, :product_category, :string#受注分類
      add_column :products, :product_kind, :string#商品の種類
      add_column :products, :shitadori, :integer#下取価格
      add_column :products, :uchikin, :integer#内金額
      add_column :products, :price, :integer#差額-ご請求額
      add_column :products, :free_space2, :text#備考
      add_column :products, :pay_string, :string#入金日
      add_column :products, :uchikin_pay_string, :string#内金入金日
      add_column :products, :staff_id, :string#担当者名
      add_column :products, :customer_name, :string#お客様名
      add_column :products, :custmer_adress, :text#お客様住所
      add_column :products, :customer_telephone, :string#お客様ご連絡先
      add_column :products, :customer_appearnce, :text#お客様-ご来店の様子-※必須入力
      add_column :products, :next_expected, :string#次回の期待が持てる方
      add_column :products, :visit_reason, :string#ｱﾝｹｰﾄ-ご来店のきっかけ
      add_column :products, :search_keywords, :text#ｱﾝｹｰﾄ-検索ｷｰﾜｰﾄﾞ
      add_column :products, :show_string_hp, :string#ｱﾝｹｰﾄ-HP閲覧の時期-?日前
      add_column :products, :browser, :string#ｱﾝｹｰﾄ-検索ｴﾝｼﾞﾝ
      add_column :products, :terminal_kind, :string#ｱﾝｹｰﾄ-端末の種類
      add_column :products, :hp_inpression, :string#ｱﾝｹｰﾄ-HPの印象
      add_column :products, :sample_price, :string#ｱﾝｹｰﾄ-ｵｰﾀﾞｰｻﾝﾌﾟﾙ価格
      add_column :products, :sample_design, :string#ｱﾝｹｰﾄ-ｵｰﾀﾞｰｻﾝﾌﾟﾙﾃﾞｻﾞｲﾝ
      add_column :products, :reason_of_yumejitate, :string#ｱﾝｹｰﾄ-夢仕立を選んだ理由
      add_column :products, :bad_impression_hp, :string#ｱﾝｹｰﾄ-HPの気になった所
      add_column :products, :want_jewelry, :string#ｱﾝｹｰﾄ-今後欲しいｼﾞｭｴﾘｰ
      add_column :products, :publish_true, :string#ｱﾝｹｰﾄ-掲載許可
      add_column :products, :contact_true, :string#ｱﾝｹｰﾄ-ﾒｰﾙ連絡許可
      add_column :products, :custmer_email, :string#ｱﾝｹｰﾄ-ﾒｰﾙｱﾄﾞﾚｽ
      add_column :products, :sex, :string#ｱﾝｹｰﾄ-性別
      add_column :products, :age, :string#ｱﾝｹｰﾄ-年代
      add_column :products, :registration_string, :string#登録日
      add_column :products, :upstring_string, :string#更新日
      add_column :products, :registration_no, :string#取引状態（継続=0、完了=1、禁止=9）
      add_column :products, :history_number, :string#履歴件数
      add_column :products, :DM_true, :string#DM可否(0=可、1=不可)
      add_column :products, :last_response_string, :string#前回対応日時
      add_column :products, :agelast_user_id, :string#前回担当者
      add_column :products, :last_respons_result, :string#前回対応結果
      add_column :products, :last_special_topics, :text#前回詳細メモ
      add_column :products, :customer_evaluation, :string#顧客評価
  end
end
